### ISSUE TITLE
hassio unstable because of IO loop

### ISSUE THREAD

**Issue by unbreakmat** [PTST/O365-HomeAssistant#62] opened 2020-05-09 12:43 UTC
2020-05-09 08:51:45 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for o365 doing I/O at custom_components/o365/calendar.py, line 158: limit=self.limit, query=query, include_recurring=True

Got this error like 1000 of times and hassio works unstbale because of this
how to fix?

**Comment by PTST** [comment] 2020-05-11 11:16
Duplicate of #57

**Closed by PTST** 2020-05-11 11:16 UTC
Labels: duplicate
